


server:
  port: 8766

spring:
  application:
    name: SERVICE-ZUUL #服务之间的调用都是根据这个 name

eureka:
  client:
  service-url:
    defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    api-a:
      path: /api-a/**
      service-id: SERVICE-RIBBON
    api-b:
      path: /api-b/**
      service-id: SERVICE-FEIGN